# Generated by Django 4.0.4 on 2022-04-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_experience',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
