# Generated by Django 4.0.4 on 2022-04-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_education_experience_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
