# Generated by Django 4.0.4 on 2022-05-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_project_expanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
