# Generated by Django 4.0.4 on 2022-04-27 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_education_experience_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.education_experience')),
            ],
        ),
    ]
