# Generated by Django 4.0.4 on 2022-04-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_remove_skillused_detail_skillused_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
