# Generated by Django 4.0.4 on 2022-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_resume_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
