# Generated by Django 4.0.4 on 2022-04-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_detail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.section'),
        ),
    ]
