# Generated by Django 4.0.4 on 2022-04-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_project_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.section'),
        ),
    ]
