# Generated by Django 4.0.4 on 2022-04-28 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_project_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.section'),
        ),
        migrations.RemoveField(
            model_name='section',
            name='resume',
        ),
        migrations.AddField(
            model_name='section',
            name='resume',
            field=models.ManyToManyField(to='resume.resume'),
        ),
    ]
